DATAPATH="../data"
SOFTWAREPATH="../software"

rule twopoint:
  input: DATAPATH + "/Microstructure.npy"
  output: DATAPATH + "/twopoint12.npy"
  shell:
    "python " + SOFTWAREPATH + "/twopoint2.py --input_filename={input} --output_filename={output}"
